{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/500\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-01-30 21:10:32.599736: I tensorflow/core/framework/local_rendezvous.cc:405] Local rendezvous is aborting with status: INVALID_ARGUMENT: Incompatible shapes: [10] vs. [16]\n",
      "\t [[{{function_node __forward_custom_loss_56735}}{{node mul}}]]\n"
     ]
    },
    {
     "ename": "InvalidArgumentError",
     "evalue": "Graph execution error:\n\nDetected at node mul defined at (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/usr/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/tmp/ipykernel_501929/598416022.py\", line 112, in <module>\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 368, in fit\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 216, in function\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 129, in multi_step_on_iterator\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 110, in one_step_on_data\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 59, in train_step\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/trainers/trainer.py\", line 399, in _compute_loss\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/trainers/trainer.py\", line 367, in compute_loss\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/trainers/compile_utils.py\", line 692, in __call__\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/trainers/compile_utils.py\", line 701, in call\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/losses/loss.py\", line 67, in __call__\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/losses/losses.py\", line 33, in call\n\n  File \"/tmp/ipykernel_501929/598416022.py\", line 91, in custom_loss\n\nIncompatible shapes: [10] vs. [16]\n\t [[{{node mul}}]] [Op:__inference_multi_step_on_iterator_61372]",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mInvalidArgumentError\u001b[0m                      Traceback (most recent call last)",
      "Cell \u001b[0;32mIn[4], line 112\u001b[0m\n\u001b[1;32m    107\u001b[0m reduce_lr \u001b[38;5;241m=\u001b[39m ReduceLROnPlateau(\n\u001b[1;32m    108\u001b[0m     monitor\u001b[38;5;241m=\u001b[39m\u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mval_loss\u001b[39m\u001b[38;5;124m\"\u001b[39m, factor\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0.5\u001b[39m, patience\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m15\u001b[39m, min_lr\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m1e-6\u001b[39m, verbose\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m1\u001b[39m\n\u001b[1;32m    109\u001b[0m )\n\u001b[1;32m    111\u001b[0m \u001b[38;5;66;03m# Train with optimal parameters\u001b[39;00m\n\u001b[0;32m--> 112\u001b[0m history \u001b[38;5;241m=\u001b[39m \u001b[43mmodel\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\n\u001b[1;32m    113\u001b[0m \u001b[43m    \u001b[49m\u001b[43mX_train_scaled\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    114\u001b[0m \u001b[43m    \u001b[49m\u001b[43my_train_scaled\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    115\u001b[0m \u001b[43m    \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m500\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m    116\u001b[0m \u001b[43m    \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m16\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m    117\u001b[0m \u001b[43m    \u001b[49m\u001b[43mvalidation_split\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m0.2\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m    118\u001b[0m \u001b[43m    \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m[\u001b[49m\u001b[43mearly_stopping\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mreduce_lr\u001b[49m\u001b[43m]\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    119\u001b[0m \u001b[43m    \u001b[49m\u001b[43mverbose\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m1\u001b[39;49m\u001b[43m,\u001b[49m\n\u001b[1;32m    120\u001b[0m \u001b[43m)\u001b[49m\n\u001b[1;32m    122\u001b[0m \u001b[38;5;66;03m# Evaluate\u001b[39;00m\n\u001b[1;32m    123\u001b[0m test_loss \u001b[38;5;241m=\u001b[39m model\u001b[38;5;241m.\u001b[39mevaluate(X_test_scaled, y_test_scaled, verbose\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m0\u001b[39m)\n",
      "File \u001b[0;32m~/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py:122\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[0;34m(*args, **kwargs)\u001b[0m\n\u001b[1;32m    119\u001b[0m     filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m    120\u001b[0m     \u001b[38;5;66;03m# To get the full stack trace, call:\u001b[39;00m\n\u001b[1;32m    121\u001b[0m     \u001b[38;5;66;03m# `keras.config.disable_traceback_filtering()`\u001b[39;00m\n\u001b[0;32m--> 122\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m\n\u001b[1;32m    123\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[1;32m    124\u001b[0m     \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[0;32m~/Documentations/Shanky/.venv/lib/python3.10/site-packages/tensorflow/python/eager/execute.py:53\u001b[0m, in \u001b[0;36mquick_execute\u001b[0;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[1;32m     51\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[1;32m     52\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[0;32m---> 53\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[1;32m     54\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[1;32m     55\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m     56\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[0;31mInvalidArgumentError\u001b[0m: Graph execution error:\n\nDetected at node mul defined at (most recent call last):\n  File \"/usr/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/usr/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel_launcher.py\", line 18, in <module>\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/traitlets/config/application.py\", line 1075, in launch_instance\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 739, in start\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 205, in start\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/usr/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 545, in dispatch_queue\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 534, in process_one\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 437, in dispatch_shell\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 362, in execute_request\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 778, in execute_request\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 449, in do_execute\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 549, in run_cell\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3075, in run_cell\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3130, in _run_cell\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 128, in _pseudo_sync_runner\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3334, in run_cell_async\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3517, in run_ast_nodes\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3577, in run_code\n\n  File \"/tmp/ipykernel_501929/598416022.py\", line 112, in <module>\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 117, in error_handler\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 368, in fit\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 216, in function\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 129, in multi_step_on_iterator\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 110, in one_step_on_data\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/backend/tensorflow/trainer.py\", line 59, in train_step\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/trainers/trainer.py\", line 399, in _compute_loss\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/trainers/trainer.py\", line 367, in compute_loss\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/trainers/compile_utils.py\", line 692, in __call__\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/trainers/compile_utils.py\", line 701, in call\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/losses/loss.py\", line 67, in __call__\n\n  File \"/home/sic/Documentations/Shanky/.venv/lib/python3.10/site-packages/keras/src/losses/losses.py\", line 33, in call\n\n  File \"/tmp/ipykernel_501929/598416022.py\", line 91, in custom_loss\n\nIncompatible shapes: [10] vs. [16]\n\t [[{{node mul}}]] [Op:__inference_multi_step_on_iterator_61372]"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.model_selection import train_test_split\n",
    "from sklearn.preprocessing import RobustScaler\n",
    "import tensorflow as tf\n",
    "from tensorflow.keras.models import Sequential\n",
    "from tensorflow.keras.layers import Dense, Dropout, BatchNormalization\n",
    "from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau\n",
    "from tensorflow.keras.optimizers import Adam\n",
    "from tensorflow.keras.regularizers import l1_l2\n",
    "from tensorflow.keras.losses import MeanSquaredError\n",
    "\n",
    "# Load data\n",
    "data = pd.read_csv(\"DATA.csv\")\n",
    "\n",
    "# Split features and target\n",
    "X = data.iloc[:, :]  # Use all columns as features\n",
    "y = data.iloc[:, :]  # Predict all columns\n",
    "\n",
    "# Split data with stratification\n",
    "X_train, X_test, y_train, y_test = train_test_split(\n",
    "    X, y, test_size=0.15, random_state=42\n",
    ")\n",
    "\n",
    "# Use RobustScaler to handle outliers better\n",
    "scaler_X = RobustScaler()\n",
    "scaler_y = RobustScaler()\n",
    "\n",
    "X_train_scaled = scaler_X.fit_transform(X_train)\n",
    "X_test_scaled = scaler_X.transform(X_test)\n",
    "y_train_scaled = scaler_y.fit_transform(y_train)\n",
    "y_test_scaled = scaler_y.transform(y_test)\n",
    "\n",
    "\n",
    "def build_model(input_dim, output_dim):\n",
    "    model = Sequential()\n",
    "\n",
    "    # Input layer\n",
    "    model.add(Dense(256, activation=\"elu\", kernel_regularizer=l1_l2(l1=1e-6, l2=1e-5)))\n",
    "    model.add(BatchNormalization())\n",
    "    model.add(Dropout(0.2))\n",
    "\n",
    "    # First hidden block - larger capacity\n",
    "    model.add(Dense(512, activation=\"elu\", kernel_regularizer=l1_l2(l1=1e-6, l2=1e-5)))\n",
    "    model.add(BatchNormalization())\n",
    "    model.add(Dropout(0.25))\n",
    "\n",
    "    # Second hidden block\n",
    "    model.add(Dense(256, activation=\"elu\", kernel_regularizer=l1_l2(l1=1e-6, l2=1e-5)))\n",
    "    model.add(BatchNormalization())\n",
    "    model.add(Dropout(0.25))\n",
    "\n",
    "    # Third hidden block\n",
    "    model.add(Dense(128, activation=\"elu\", kernel_regularizer=l1_l2(l1=1e-6, l2=1e-5)))\n",
    "    model.add(BatchNormalization())\n",
    "    model.add(Dropout(0.2))\n",
    "\n",
    "    # Fourth hidden block\n",
    "    model.add(Dense(64, activation=\"elu\", kernel_regularizer=l1_l2(l1=1e-6, l2=1e-5)))\n",
    "    model.add(BatchNormalization())\n",
    "    model.add(Dropout(0.15))\n",
    "\n",
    "    # Output layer\n",
    "    model.add(Dense(output_dim, activation=\"linear\"))\n",
    "\n",
    "    return model\n",
    "\n",
    "\n",
    "# Initialize model with correct input shape\n",
    "model = build_model(X_train_scaled.shape[1], y_train_scaled.shape[1])\n",
    "\n",
    "# Custom learning rate schedule\n",
    "initial_learning_rate = 0.001\n",
    "decay_steps = 1000\n",
    "decay_rate = 0.9\n",
    "learning_rate_schedule = tf.keras.optimizers.schedules.ExponentialDecay(\n",
    "    initial_learning_rate, decay_steps, decay_rate\n",
    ")\n",
    "\n",
    "\n",
    "# Define custom loss using tf.keras backend operations\n",
    "@tf.function\n",
    "def custom_loss(y_true, y_pred):\n",
    "    # Calculate MSE manually\n",
    "    mse = tf.reduce_mean(tf.square(y_true - y_pred), axis=-1)\n",
    "    # Weights for different parameters\n",
    "    weights = tf.constant(\n",
    "        [1.0, 1.0, 1.0, 1.0, 1.0, 1.5, 1.0, 2.0, 1.5, 1.0], dtype=tf.float32\n",
    "    )\n",
    "    # Apply weights to the MSE\n",
    "    weighted_mse = mse * weights\n",
    "    return tf.reduce_mean(weighted_mse)\n",
    "\n",
    "\n",
    "optimizer = Adam(learning_rate=learning_rate_schedule)\n",
    "model.compile(optimizer=optimizer, loss=custom_loss, metrics=[\"mae\"])\n",
    "\n",
    "# Enhanced callbacks\n",
    "early_stopping = EarlyStopping(\n",
    "    monitor=\"val_loss\",\n",
    "    patience=40,\n",
    "    restore_best_weights=True,\n",
    "    verbose=1,\n",
    "    min_delta=1e-4,\n",
    ")\n",
    "\n",
    "reduce_lr = ReduceLROnPlateau(\n",
    "    monitor=\"val_loss\", factor=0.5, patience=15, min_lr=1e-6, verbose=1\n",
    ")\n",
    "\n",
    "# Train with optimal parameters\n",
    "history = model.fit(\n",
    "    X_train_scaled,\n",
    "    y_train_scaled,\n",
    "    epochs=500,\n",
    "    batch_size=16,\n",
    "    validation_split=0.2,\n",
    "    callbacks=[early_stopping, reduce_lr],\n",
    "    verbose=1,\n",
    ")\n",
    "\n",
    "# Evaluate\n",
    "test_loss = model.evaluate(X_test_scaled, y_test_scaled, verbose=0)\n",
    "print(f\"\\nTest Loss: {test_loss:.4f}\")\n",
    "\n",
    "# Save model\n",
    "model.save(\"water_quality_ann_enhanced.h5\")\n",
    "\n",
    "# Visualize results\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "\n",
    "def plot_training_history(history):\n",
    "    fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))\n",
    "\n",
    "    # Plot loss\n",
    "    ax1.plot(history.history[\"loss\"], label=\"Training Loss\")\n",
    "    ax1.plot(history.history[\"val_loss\"], label=\"Validation Loss\")\n",
    "    ax1.set_title(\"Model Loss\")\n",
    "    ax1.set_xlabel(\"Epoch\")\n",
    "    ax1.set_ylabel(\"Loss\")\n",
    "    ax1.legend()\n",
    "    ax1.grid(True)\n",
    "\n",
    "    # Plot MAE\n",
    "    ax2.plot(history.history[\"mae\"], label=\"Training MAE\")\n",
    "    ax2.plot(history.history[\"val_mae\"], label=\"Validation MAE\")\n",
    "    ax2.set_title(\"Model MAE\")\n",
    "    ax2.set_xlabel(\"Epoch\")\n",
    "    ax2.set_ylabel(\"MAE\")\n",
    "    ax2.legend()\n",
    "    ax2.grid(True)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(\"training_metrics.png\")\n",
    "    plt.close()\n",
    "\n",
    "\n",
    "plot_training_history(history)\n",
    "\n",
    "# Make predictions and analyze results\n",
    "predictions = model.predict(X_test_scaled)\n",
    "predictions = scaler_y.inverse_transform(predictions)\n",
    "actual = scaler_y.inverse_transform(y_test_scaled)\n",
    "\n",
    "# Calculate and print R-squared for each parameter\n",
    "for i, column in enumerate(data.columns):\n",
    "    correlation_matrix = np.corrcoef(actual[:, i], predictions[:, i])\n",
    "    r_squared = correlation_matrix[0, 1] ** 2\n",
    "    print(f\"{column} R-squared: {r_squared:.4f}\")\n",
    "\n",
    "# Print mean absolute percentage error for each parameter\n",
    "mape = np.mean(np.abs((actual - predictions) / actual), axis=0) * 100\n",
    "for i, column in enumerate(data.columns):\n",
    "    print(f\"{column} MAPE: {mape[i]:.2f}%\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": ".venv",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
